### ISSUE TITLE
No date range end in `intervals()` 

### ISSUE THREAD

**Issue by dbrojas** [remi-dupre/opening-hours-rs#24]
With regular use we get end dates from the RangeIterator:

```python
>>> from opening_hours import OpeningHours
>>> oh = OpeningHours("2022-2023")
>>> next(oh.intervals(start=datetime(2022, 1, 1)))
(datetime.datetime(2022, 1, 1, 0, 0), datetime.datetime(2024, 1, 1, 0, 0), 'open', [])
```

But with this specific syntax (adding month/date) the end date is empty:
```python
>>> oh = OpeningHours("2022 Jan 1-2023 Dec 31")
>>> next(oh.intervals(start=datetime(2022, 1, 1)))
(datetime.datetime(2022, 1, 1, 0, 0), None, 'open', [])
```

Could this be a bug or is this intended?

**Comment by remi-dupre** [comment]
Hey man, thanks for the feedback!
This was indeed a bug, I've just fixed it in https://github.com/remi-dupre/opening-hours-rs/pull/25/commits/873b80c7f316dd85b8e7039a29bcf4269bf9ba39 and it is deployed in the newer 0.5.6 release :+1:
