### ISSUE TITLE
Cannot install the latest version with pip

### ISSUE THREAD

**Issue by qloridant** [remi-dupre/opening-hours-rs#30]
Hi ! 
## Running
`pip install opening-hours` or `pip install opening-hours==0.6.4` (or any version from 0.6.0)

## Error
```
Collecting opening-hours-py==0.6.0
  Using cached opening_hours_py-0.6.0.tar.gz (13 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      
      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/
      
      Checking for Rust toolchain....
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

## Configuration

- OS : Ubuntu 20
- Python : 3.9.12

## Solution
To install the package with PyPi, I must force the version to v0.5.6

**Comment by remi-dupre** [comment]
Hi!

Latest version should work for Python 3.7 and above, on Linux/MacOS/Windows and most architectures. Does it work on your side?

**Comment by amelie-rondot** [comment]
Hello,
I've just tried with both v0.6.0 and v0.6.4, in the both cases it still does not work, and the same error message related by @qloridant in this issue still appears.

**Comment by remi-dupre** [comment]
Have you tried v0.6.17 ? (Yeah, tweaking the CI required to bump versions quite a lot :grimacing:) Older versions don't chip with cross-compiled packages and have fewer available Python versions.

**Comment by amelie-rondot** [comment]
Yes, it does work with v0.6.17, thank you :)

**Comment by remi-dupre** [comment]
That's great to hear! I didn't have the complexity of packaging a compiled module for various Python versions, on various OS and over various CPU architectures when I first released this library :sweat_smile:
