### ISSUE TITLE
SyntaxError for open end time

### ISSUE THREAD

**Issue by KristjanESPERANTO** [remi-dupre/opening-hours-rs#37]
I'm trying to use the python package. When I'm handling a time string with open end (like `Mo-Su 11:30+`) I get a SyntaxError.

```
SyntaxError: could not parse expression:
using an unsupported feature: point in time
```

Open end time is part of the specification: https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification

**Comment by remi-dupre** [comment]
Hi!

While it's not a full-featured support yet, it doesn't raise an exception.

Current behavior is to assume that it may be open until midnight that day.

```python
>>> from opening_hours import OpeningHours
>>> oh = OpeningHours("Mo-Su 11:30+")
>>> oh.next_change()
datetime.datetime(2024, 12, 30, 0, 0)
```
