### ISSUE TITLE
Installation fails on python:3.1*-alpine, but works on ubuntu 22.04 docker images

### ISSUE THREAD

**Issue by the-infinity** [remi-dupre/opening-hours-rs#38]
As stated in the title, for some reason it works at ubuntu 22.04, but does not python:3.10-alpine or python:3.11-alpine. Same amd64 maschine, same error as in issue #30  : 

```
#13 26.98   Preparing metadata (pyproject.toml): finished with status 'error'
#13 26.99   error: subprocess-exited-with-error
#13 26.99   
#13 26.99   × Preparing metadata (pyproject.toml) did not run successfully.
#13 26.99   │ exit code: 1
#13 26.99   ╰─> [6 lines of output]
#13 26.99       Checking for Rust toolchain....
#13 26.99       
#13 26.99       Cargo, the Rust package manager, is not installed or is not on PATH.
#13 26.99       This package requires Rust and Cargo to compile extensions. Install it through
#13 26.99       the system's package manager or via https://rustup.rs/
#13 26.99       
#13 26.99       [end of output]
```

I would guess the binary for alpine is missing, although I find it quite strange that the result differs on the linux distro with same python version and same architecture.

**Comment by remi-dupre** [comment]
I've added support to more targets since then, but that might still not do the trick as alpine doesn't ship glibc by default. Poetry can manage to build the package but it requires to install rust or rustup. I'll try to add some documentation in the readme but if someone has actual experience with that I'm interested.

**Comment by the-infinity** [comment]
Sadly, this does not really help, not even installing `gcompat` via apk, so sadly I found no way to run it in Alpine.

It is super-tricky in general: version 0.6 does work at Ubuntu 22.04 = Python 3.10, but not at Ubuntu 24.04 = Python 3.12. With 0.8 it's the other way round: works with Ubuntu 24.04 = Python 3.12, but not with Ubuntu 22.04 = Python 3.10.

**Comment by remi-dupre** [comment]
That's a bit clunky but I managed to install the library with this minimal example :

```dockerfile
FROM python:3.12-alpine
RUN apk add alpine-sdk rustup
RUN rustup-init -y --profile minimal
RUN source "$HOME/.cargo/env" && pip install opening-hours-py
```

Those extra packages are already required to compile the library, so I'd recommend installing the library in a venv from a builder step and then just copying the venv in the released image :shrug: (assuming you are trying to build a docker image)

**Comment by remi-dupre** [comment]
Hi!

The workaround is no longer required for version >= `0.10.0` which now includes a binary build for musl :partying_face: (PyO3 is awesome, it came for free)

Tested by building this Dockerfile :

```dockerfile
FROM python:3.12-alpine
RUN pip install opening-hours-py
```
