### ISSUE TITLE
Comparing two opening hours strings

### ISSUE THREAD

**Issue by matkoniecz** [remi-dupre/opening-hours-rs#44]
Is it possible to use this library to compare whether two opening hours strings have effectively the same meaning?

I wanted to use this for import verification/checking but it seems that it would be impossible - there is `oh.intervals()` but it would not help as iterating over infinite iterator has obvious problems.

Is it possible to generate canonical form already? Or add functionality to do this?

**Comment by remi-dupre** [comment]
That certainly sound like an interesting feature.

Is there already some kind of specification for a canonical form?

**Comment by matkoniecz** [comment]
AFAIK not really, it is mostly matter of taste :(

maybe it would be possible to expose parsed structure of opening hours? Not just infinite `oh.intervals()`? (or maybe it is accessible somehow and I have not figured out how?)

**Comment by remi-dupre** [comment]
With 0.8.0 `OpeningHours` implements `__eq__` (and `__hash__` btw) which should help to identify **very basic** variations of the same expressions. I might spent time improving this but any suggestion is welcome, maybe we should close this issue and create new issues if any suggestion comes to your mind?

There is now also a `__str__` if you prefer to work with strings.

Also, exposing the parsed AST would require its own issue, I'm not super into it if you don't specifically need it. It would require a wrapper for most Python types which is not trivial as there are many algebraic types involved. Although, note that the Rust core does expose the AST in a small parsing crate : https://docs.rs/opening-hours-syntax/0.8.0/opening_hours_syntax/

**Comment by remi-dupre** [comment]
I'm closing this issue, I'd recommend something like `str(OpeningHours(expr_1)) == str(OpeningHours(expr_2))`.

For any issue are suggestion for rules in this feature, issues are welcome.
