### ISSUE TITLE
Hour only hours seem to not get picked up in multi-day intervals

### ISSUE THREAD

**Issue by tim-x-y-z** [remi-dupre/opening-hours-rs#56]
Hey, thanks for the great library! 

There seem to an issue when opening hours are passed using only the hours (and no days) and querying the `.intervals` using a different day from `start` to `end`.

`OpeningHours("00:30-05:30").intervals(datetime(2024, 11, 25, 17, 30), datetime(2024, 11, 26, 9, 0))` doesn't return any open hours.
`OpeningHours("00:30-05:30").intervals(datetime(2024, 11, 26, 0, 0), datetime(2024, 11, 26, 9, 0))` does return the expected open hours.

However, this is not an issue if we prepend the string with `Mo-Su`. 

I assume we would want the output of `Mo-Su 00:30-05:30` to be the same as `00:30-05:30`. But perhaps that is wrong, and the current implementation / behaviour is intended ! 

# Reproducible example
## Version
```python
import pkg_resources
package_version = pkg_resources.get_distribution('opening-hours-py').version
package_version
Out: '0.8.3'
```

## Example
I assume we would want both of those output to be the same:

```python
from opening_hours import OpeningHours
from datetime import datetime, UTC
start = datetime(2024, 11, 25, 17, 30, tzinfo=UTC)
end = datetime(2024, 11, 26, 9, 0, tzinfo=UTC)
hours_that_works = "Mo-Su 00:30-05:30"
hours_that_dont = "00:30-05:30"
interval_fine = OpeningHours(hours_that_works).intervals(start.replace(tzinfo=None), end.replace(tzinfo=None))
interval_not_fine = OpeningHours(hours_that_dont).intervals(start.replace(tzinfo=None), end.replace(tzinfo=None))
print("######### Hours prepended with Mo-Su #########")
for i in interval_fine:
    print(i)
print("######### Hours only #########")
for i in interval_not_fine:
    print(i)

# Output:
    
######### Hours prepended with Mo-Su #########
(datetime.datetime(2024, 11, 25, 17, 30), datetime.datetime(2024, 11, 26, 0, 30), 'closed', [])
(datetime.datetime(2024, 11, 26, 0, 30), datetime.datetime(2024, 11, 26, 5, 30), 'open', [])
(datetime.datetime(2024, 11, 26, 5, 30), datetime.datetime(2024, 11, 26, 9, 0), 'closed', [])
######### Hours only #########
(datetime.datetime(2024, 11, 25, 17, 30), datetime.datetime(2024, 11, 26, 9, 0), 'closed', [])

```

**Comment by remi-dupre** [comment]
Hi!

Thank you for the detailed issue & example 😄 

This should be fixed with 0.9.1 which was just released 👍
